name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set up environment variables
        run: |
          echo "API_USERNAME=${{ secrets.API_USERNAME }}" >> .env
          echo "API_PASSWORD=${{ secrets.API_PASSWORD }}" >> .env
          echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> .env
          echo "FLASK_ENV=production" >> .env
          echo "FLASK_APP=app.py" >> .env

      - name: Start Gunicorn
        run: |
          gunicorn -c gunicorn_config.py app:app &
          sleep 5  # Give Gunicorn time to start

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          cname: ${{ secrets.CUSTOM_DOMAIN }}  # Optional: if you have a custom domain
